# Generated by Django 6.0.3 on 2026-03-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteitem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
